CREATE TABLE gdp (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE unrate (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE DFF (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE CPIENGSL (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GFDEBTN (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CORESTICKM159SFRBATL (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
