CREATE TABLE unemployment_rate (
    RELEASE_DATE TIMESTAMP PRIMARY KEY,
    DATA_VALUE NUMERIC,
    RELEASE_JDN NUMERIC,
    CAL_QUARTER_KEY VARCHAR(10),
    FIRST_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);